name: flutterbase
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.3+34

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter_spinkit: ^5.1.0
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  animations: ^2.0.1
  card_swiper: ^2.0.4
  flutter_svg: ^2.0.5
  dio: ^4.0.0
  flutter_markdown: ^0.6.6
  shared_preferences: ^2.0.7
  url_launcher: ^6.0.11
  form_field_validator: ^1.1.0
  flutter_form_builder: ^8.0.0
  image_picker: ^0.8.4+2
  pull_to_refresh: ^2.0.0
  google_fonts: ^4.0.3
  line_icons: ^2.0.1
  localstorage: ^4.0.0+1
  pin_code_fields: ^7.4.0
  flutter_datetime_picker:
    git: https://github.com/Realank/flutter_datetime_picker.git
  get: ^4.6.5
  file_picker: ^5.2.2
  flutter_rating_bar: ^4.0.1
  http_parser: ^4.0.2
  dotted_line: ^3.1.0
  flutter_inappwebview: ^5.7.2+2
  package_info_plus: ^3.1.1
  faker: ^2.1.0
  substring_highlight: ^1.0.33
  mask_text_input_formatter: ^2.4.0
  http_query_string: ^1.0.0
  date_format: ^2.0.7
  syncfusion_flutter_pdfviewer: ^21.1.39
  flutter_file_view: ^2.1.2
  path_provider: ^2.0.11
  internet_file: ^1.2.0
  share_plus: ^6.3.0
  event_bus: ^2.0.0
  carousel_slider: ^4.2.1
  provider: ^6.0.5
  flutter_slidable: ^3.0.0
  rxdart: ^0.27.7
  expandable: ^5.0.1
  curl_logger_dio_interceptor: ^0.0.3
  rive: ^0.10.3
  currency_text_input_formatter: ^2.1.7
  slider_captcha: ^1.0.0
  flutter_localization: ^0.1.12
  flutter_typeahead: ^4.6.2
  photo_view: ^0.14.0
  flutter_phosphor_icons: ^0.0.1+6
  dotted_border: ^2.0.0+3

dev_dependencies:
  build_runner: ^2.0.0
  json_serializable: ^6.3.1
  change_app_package_name: ^1.1.0
  cider: ^0.1.1
  flutter_test:
    sdk: flutter

# it's a hack and shouldn't be used in production, it does the job to run the app in certain circumstances
dependency_overrides:
  intl: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
    - assets/dist/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  fonts:
      - family: SfProDisplayBold
        fonts:
          - asset: assets/fonts/sfprodisplay/SFPRODISPLAYBOLD.OTF

      - family: SfProDisplayMedium
        fonts:
          - asset: assets/fonts/sfprodisplay/SFPRODISPLAYREGULAR.OTF

      - family: SfProDisplayRegular
        fonts:
          - asset: assets/fonts/sfprodisplay/SFPRODISPLAYREGULAR.OTF

  #
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
